{
 "title": "Engine metrics",
 "tags": [ "startpage" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(minetest_core_server_packet_recv_processed, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minetest_core_server_uptime{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minetest_core_player_number{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Active blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minetest_env_active_blocks{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Active objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minetest_env_active_objects{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Loaded blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minetest_map_loaded_blocks{instance=\"${instance}\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Player count / Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minetest_core_player_number{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "minetest_core_latency{instance=\"$instance\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Received packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(minetest_core_server_packet_recv{instance=\"$instance\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(minetest_core_server_packet_recv_processed{instance=\"$instance\"}[5m])",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Number of active object messages generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(minetest_core_aom_generated_count{instance=\"${instance}\"}[30s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of completed emerges with status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(minetest_emerge_completed{instance=\"${instance}\"}[30s])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Map edit events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "irate(minetest_core_map_edit_events{instance=\"${instance}\"}[30s])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Received packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(minetest_core_server_packet_recv{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(minetest_core_server_packet_recv_processed{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "Active blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "minetest_env_active_blocks{instance=\"${instance}\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Active objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "minetest_env_active_objects{instance=\"${instance}\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Block load/save count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(minetest_map_saved_blocks{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Saved"
    },
    {
     "expr": "rate(minetest_map_loaded_blocks{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Loaded"
    }
   ]
  },
  {
   "title": "Time spent in environment step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(minetest_env_step_time{instance=\"${instance}\"}[30s])",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Block save time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(minetest_map_save_time{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Save time"
    }
   ]
  }
 ]
}